spring:
    application:
        name: ComarchECMtext
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration

    datasource:
        url: jdbc:sqlserver://10.132.54.147;databaseName=BP_GER-PORTAL-TEST;instanceName=MSSQL2016_IMP;
        username: BP_GER-PORTAL-TEST
        password: pass
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        database: SQL_SERVER
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            hibernate.cache.hazelcast.instance_name: ComarchECMtext
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true
security:
    basic:
        enabled: false
    ignored: /**

application:
    property: test