spring:
    application:
        name: ComarchECMtext
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration

security:
    basic:
        enabled: false
    ignored: /**

application:
    property: test